---
- hosts: all
  sudo: yes
  tasks:
  # lets start with pip and necessities
  - name: Install build-essential
    apt: pkg=build-essential state=installed update_cache=true
  - name: Install python-dev
    apt: pkg=python-dev state=installed update_cache=true
  - name: Install python-pip
    apt: pkg=python-pip state=installed update_cache=true
