---
- hosts: all
  sudo: yes
  gather_facts: yesy
#  tasks:
  # lets start with pip and necessities
#  - name: Install build-essential
#    apt: pkg=build-essential state=installed update_cache=true
#  - name: Install python-dev
#    apt: pkg=python-dev state=installed update_cache=true
#  - name: Install python-pip
#    apt: pkg=python-pip state=installed update_cache=true
  # lets update pip and virtualenv
#  - name: Update pip and virtualenv
#    shell: "pip install --upgrade pip"
#    shell: "pip install --upgrade virtualenv"
  # lets actuall install django 
#  - name: Install django
#    pip: name=django state=present
#- hosts: all
#  sudo: no
#  tasks:
  # lets actuall start building a web site
#  - name: lets make the project directory
#    command: django-admin.py startproject johnhayden
#    args:
#      creates: /home/vagrant/johnhayden/manage.py

